title: Tintamarre
author:
  name: MATsxm for CaribThemes
  email: 'contact@caribthemes.io'
  gravatar: mat@idimweb.com
metadata:
    description: 'A FREE responsive Theme based on Bootstrap & ported to Grav by CaribThemes.'